[[shards]]
name = "AatirKhan"
idx = 0
address = "127.0.0.2:8080"
replicas = ["127.0.0.22:8080"]

[[shards]]
name = "AbdulSamad"
idx = 1
address = "127.0.0.3:8080"
replicas = ["127.0.0.33:8080"]

[[shards]]
name = "AliFarhat"
idx = 2
address = "127.0.0.4:8080"
replicas = ["127.0.0.44:8080"]

[[shards]]
name = "AmalSaqib"
idx = 3
address = "127.0.0.5:8080"
replicas = ["127.0.0.55:8080"]

[[shards]]
name = "AtoofaAkhtar"
idx = 4
address = "127.0.0.6:8080"
replicas = ["127.0.0.66:8080"]

[[shards]]
name = "ArshanullahTawhidi"
idx = 5
address = "127.0.0.7:8080"
replicas = ["127.0.0.77:8080"]

[[shards]]
name = "AsadImtiaz"
idx = 6
address = "127.0.0.8:8080"
replicas = ["127.0.0.88:8080"]

[[shards]]
name = "AzraelOfTheCourtOfBlight"
idx = 7
address = "127.0.0.9:8080"
replicas = ["127.0.0.99:8080"]